name: lxd-mcp-server
version: '1.0'
summary: LXD MCP Server for container management
title: LXD MCP Bridge
description: |
  An MCP server that bridges between an LLM and LXD containers on the same host.

  The package will autmatically start a daemon listening on port 8005 by default.
  Point your LLM to http://127.0.0.1:8005/mcp in its MCP settings and make sure 
  to connect the lxd interface for this snap with:

    sudo snap connect lxd-mcp-server:lxd lxd:lxd

  So that the bridge can actually talk to your lxd instance.

  The MCP server provides 8 tools to your LLM that you can use:
    - list_containers (lists existing containers)
    - create_container (creates a new container, with <name> and <release>)
    - start_container (fires up the named container)
    - stop_container (stops the named container)
    - delete_container (deletes a container)
    - run_in_container (runs a command inside the container)
    - push_to_container (copies single files into the container)
    - pull_from_container (copies single files out of the container)

  There are also two config options you can use with snap set:
    - port (defaults to 8005)
    - debug (defaults ot being off)

  Note that you might need to enable the built in LLM proxy in some LLMs
  (i.e. in llama-server this is the "Use llama-server proxy" option in the 
  llama-ui)  

contact: https://github.com/ogra1/lxd-mcp-server/issues
issues: https://github.com/ogra1/lxd-mcp-server/issues
source-code: https://github.com/ogra1/lxd-mcp-server
website: https://github.com/ogra1/lxd-mcp-server
license: GPL-2.0-or-later


base: core26
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  lxd-mcp-server:
    command: bin/lxd-mcp-server
    daemon: simple
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/lib/python3.14/site-packages:$SNAP/lib/python3.14/dist-packages:$PYTHONPATH
    plugs:
      - lxd
      - network
      - network-bind

parts:
  python-deps:
    plugin: python
    source: .
    build-packages:
      - python3-pip
      - python3-dev
      - build-essential
      - libffi-dev
      - libssl-dev
      - python3.14-venv
    stage-packages:
      - python3-pip
      - python3-dev
      - build-essential
      - libffi-dev
      - libssl-dev
      - python3.14-venv
    python-packages:
      - pylxd
      - mcp
      - mcp-types
      - anyio
      - httpx2
      - jsonschema
      - opentelemetry-api
      - pydantic
      - python-multipart
      - sse-starlette
      - starlette
      - typing-inspection
      - uvicorn

  lxd-mcp-server:
    plugin: dump
    source: src/bin
    organize:
      lxd-mcp-server: bin/lxd-mcp-server

